In [27]:
# Dependencies and Setup
import pandas as pd

import numpy as np
import requests
import json
import datetime
from census import Census

In [28]:
#import census table
census_df = pd.read_csv("county_census_data.csv")
census_df.head(2)

,Name,County,Population,MedianAge,HouseholdIncome,PerCapitaIncome,UnemploymentCount,PovertyCount,PovertyRate,State,abbr,UnemploymentRate
0,"Corozal Municipio, Puerto Rico",Corozal Municipio,34933,38.1,14752,7887,3296,19146,54.807775,Puerto Rico,PR,0.094352
1,"Maunabo Municipio, Puerto Rico",Maunabo Municipio,11297,43.5,17636,8830,735,5945,52.624591,Puerto Rico,PR,0.065062

In [29]:
#import debt table
#note:  had to change the encoding from ANSI to UTF-8, I did this in notepad, save-as
debt_df = pd.read_csv("debtdata.csv")
debt_df.head()

,County,State,MedicialPercent,StudentDebtPercent,AutoDebtPercent,OtherPercent,MedicialAmount,StudentDebtAmount,AutoDebtAmount,OtherAmount,TotalDebt
0,Walker County,Alabama,0.44,0.08,0.26,0.22,81229.5,14769.0,47999.3,40614.8,184613
1,Jackson County,Alabama,0.36,0.08,0.25,0.31,66460.5,14769.0,46153.1,57229.9,152888
2,Etowah County,Alabama,0.40,0.10,0.27,0.23,73845.0,18461.3,49845.4,42460.9,149380
3,St. Clair County,Alabama,0.36,0.13,0.31,0.20,66460.5,23999.6,57229.9,36922.5,147531
4,Tuscaloosa County,Alabama,0.44,0.14,0.28,0.14,81229.5,25845.8,51691.5,25845.8,146907

In [30]:
debt_df.dtypes

County                 object
State                  object
MedicialPercent       float64
StudentDebtPercent    float64
AutoDebtPercent       float64
OtherPercent          float64
MedicialAmount        float64
StudentDebtAmount     float64
AutoDebtAmount        float64
OtherAmount            object
TotalDebt               int64
dtype: object

In [31]:
#Merge the two table on state.  Keep all.
all_data = pd.merge(census_df,debt_df, how = 'left', on = ['County','State'])
all_data.head(100)

,Name,County,Population,MedianAge,HouseholdIncome,PerCapitaIncome,UnemploymentCount,PovertyCount,PovertyRate,State,...,UnemploymentRate,MedicialPercent,StudentDebtPercent,AutoDebtPercent,OtherPercent,MedicialAmount,StudentDebtAmount,AutoDebtAmount,OtherAmount,TotalDebt
0,"Corozal Municipio, Puerto Rico",Corozal Municipio,34933,38.1,14752,7887,3296,19146,54.807775,Puerto Rico,...,0.094352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Maunabo Municipio, Puerto Rico",Maunabo Municipio,11297,43.5,17636,8830,735,5945,52.624591,Puerto Rico,...,0.065062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Peñuelas Municipio, Puerto Rico",Peñuelas Municipio,21661,36.4,16868,7983,1601,12379,57.148793,Puerto Rico,...,0.073912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Ponce Municipio, Puerto Rico",Ponce Municipio,148863,39.5,16561,10775,7013,75187,50.507514,Puerto Rico,...,0.047110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"San Sebastián Municipio, Puerto Rico",San Sebastián Municipio,38970,42.0,14275,8072,3307,21472,55.098794,Puerto Rico,...,0.084860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"Toa Alta Municipio, Puerto Rico",Toa Alta Municipio,74169,37.1,29672,14162,4266,22070,29.756367,Puerto Rico,...,0.057517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Toa Baja Municipio, Puerto Rico",Toa Baja Municipio,81905,38.9,24583,12240,6565,29279,35.747512,Puerto Rico,...,0.080154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Vieques Municipio, Puerto Rico",Vieques Municipio,8931,41.4,16261,11136,428,3260,36.502071,Puerto Rico,...,0.047923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Yabucoa Municipio, Puerto Rico",Yabucoa Municipio,35025,41.6,15586,8672,2685,18297,52.239829,Puerto Rico,...,0.076660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"Aguada Municipio, Puerto Rico",Aguada Municipio,39470,41.0,16199,9001,2538,20558,52.085128,Puerto Rico,...,0.064302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Caguas Municipio, Puerto Rico",Caguas Municipio,134269,39.7,24229,13904,8503,50442,37.567867,Puerto Rico,...,0.063328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Canóvanas Municipio, Puerto Rico",Canóvanas Municipio,46779,39.0,19986,11094,4353,19930,42.604588,Puerto Rico,...,0.093055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"Cidra Municipio, Puerto Rico",Cidra Municipio,41181,38.7,20389,10965,2653,17723,43.036837,Puerto Rico,...,0.064423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"Coamo Municipio, Puerto Rico",Coamo Municipio,39796,39.4,19110,10307,1038,19197,48.238516,Puerto Rico,...,0.026083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Dorado Municipio, Puerto Rico",Dorado Municipio,37722,39.5,29354,15495,3104,12475,33.070887,Puerto Rico,...,0.082286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"Luquillo Municipio, Puerto Rico",Luquillo Municipio,18952,39.8,19377,10434,2121,8649,45.636344,Puerto Rico,...,0.111914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"Barranquitas Municipio, Puerto Rico",Barranquitas Municipio,29237,35.5,15694,7716,797,17530,59.958272,Puerto Rico,...,0.027260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Orocovis Municipio, Puerto Rico",Orocovis Municipio,21906,37.9,14296,7326,2131,12276,56.039441,Puerto Rico,...,0.097279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"San Lorenzo Municipio, Puerto Rico",San Lorenzo Municipio,38689,40.2,18589,10497,1493,17626,45.558169,Puerto Rico,...,0.038590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"Añasco Municipio, Puerto Rico",Añasco Municipio,27892,41.3,18765,9344,1474,12618,45.238778,Puerto Rico,...,0.052847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"Ceiba Municipio, Puerto Rico",Ceiba Municipio,12238,40.9,18998,11840,472,5285,43.185161,Puerto Rico,...,0.038568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Ciales Municipio, Puerto Rico",Ciales Municipio,17325,40.5,14432,8049,844,9970,57.546898,Puerto Rico,...,0.048716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"Comerío Municipio, Puerto Rico",Comerío Municipio,19914,38.1,13523,7047,1665,11657,58.536708,Puerto Rico,...,0.083610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Isabela Municipio, Puerto Rico",Isabela Municipio,43314,40.8,16333,8798,2606,23262,53.705499,Puerto Rico,...,0.060165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,"Jayuya Municipio, Puerto Rico",Jayuya Municipio,15297,36.3,15615,7179,1203,9065,59.259986,Puerto Rico,...,0.078643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,"Lares Municipio, Puerto Rico",Lares Municipio,27321,41.1,12820,8212,3456,15252,55.825189,Puerto Rico,...,0.126496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"Las Piedras Municipio, Puerto Rico",Las Piedras Municipio,38253,38.1,20587,10342,2697,17358,45.376833,Puerto Rico,...,0.070504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"Río Grande Municipio, Puerto Rico",Río Grande Municipio,51768,40.2,22584,10804,5099,19441,37.554087,Puerto Rico,...,0.098497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"San Juan Municipio, Puerto Rico",San Juan Municipio,355181,41.8,21677,18160,22671,147147,41.428736,Puerto Rico,...,0.063829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Vega Alta Municipio, Puerto Rico",Vega Alta Municipio,38589,37.8,18053,10492,2630,19087,49.462282,Puerto Rico,...,0.068154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,"Las Marías Municipio, Puerto Rico",Las Marías Municipio,8874,40.1,14404,7154,57,5070,57.133198,Puerto Rico,...,0.006423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,"Patillas Municipio, Puerto Rico",Patillas Municipio,17769,43.3,14512,8679,1004,10182,57.302043,Puerto Rico,...,0.056503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,"Rincón Municipio, Puerto Rico",Rincón Municipio,14526,44.6,18292,10220,708,7047,48.513011,Puerto Rico,...,0.048740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,"Villalba Municipio, Puerto Rico",Villalba Municipio,23659,37.6,19893,10449,2268,11740,49.621708,Puerto Rico,...,0.095862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,"Aguas Buenas Municipio, Puerto Rico",Aguas Buenas Municipio,26855,40.4,16733,10615,1941,12910,48.072985,Puerto Rico,...,0.072277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,"Bayamón Municipio, Puerto Rico",Bayamón Municipio,188614,40.4,25528,14138,11392,63445,33.637482,Puerto Rico,...,0.060398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,"Carolina Municipio, Puerto Rico",Carolina Municipio,161684,41.1,29082,16188,10203,46686,28.874842,Puerto Rico,...,0.063105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,"Cayey Municipio, Puerto Rico",Cayey Municipio,45431,41.0,20442,12594,1746,19785,43.549559,Puerto Rico,...,0.038432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,"Monroe County, Alabama",Monroe County,21745,41.7,26036,17264,1691,7249,33.336399,Alabama,...,0.077765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,"Lawrence County, Alabama",Lawrence County,33288,42.0,43779,22419,972,5490,16.492430,Alabama,...,0.029200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,"Lee County, Alabama",Lee County,156597,31.0,47564,26170,4371,33132,21.157493,Alabama,...,0.027912,0.35,0.17,0.29,0.19,64614.4,31384.1,53537.6,35076.4,136953.0
81,"Marion County, Alabama",Marion County,30058,44.1,35719,21835,691,5175,17.216714,Alabama,...,0.022989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,"Pickens County, Alabama",Pickens County,20170,42.1,36220,20089,958,4340,21.517105,Alabama,...,0.047496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,"Sumter County, Alabama",Sumter County,13084,35.9,21663,14739,672,4398,33.613574,Alabama,...,0.051360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,"Jefferson County, Alabama",Jefferson County,659460,37.6,49321,29456,25044,113368,17.191035,Alabama,...,0.037977,0.45,0.17,0.26,0.12,83075.6,31384.1,47999.3,22153.5,115941.0
85,"Choctaw County, Alabama",Choctaw County,13188,45.8,32122,20994,468,2903,22.012436,Alabama,...,0.035487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,"Franklin County, Alabama",Franklin County,31507,37.7,39501,19314,1114,7175,22.772717,Alabama,...,0.035357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,"Marengo County, Alabama",Marengo County,19743,42.1,32255,22996,975,5000,25.325432,Alabama,...,0.049385,0.45,0.17,0.29,0.09,83075.6,31384.1,53537.6,16615.1,74335.0
88,"Russell County, Alabama",Russell County,58480,35.3,38988,21279,2465,12024,20.560876,Alabama,...,0.042151,0.51,0.17,0.28,0.04,94152.4,31384.1,51691.5,7384.5,95871.0
89,"Cherokee County, Alabama",Cherokee County,25855,46.1,40041,23010,557,4104,15.873139,Alabama,...,0.021543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,"Covington County, Alabama",Covington County,37519,43.4,39467,22431,1759,6491,17.300568,Alabama,...,0.046883,0.43,0.10,0.25,0.22,79383.4,18461.3,46153.1,40614.8,140630.0
91,"Crenshaw County, Alabama",Crenshaw County,13866,41.4,38937,21580,389,2399,17.301313,Alabama,...,0.028054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,"Dallas County, Alabama",Dallas County,40755,39.3,30065,18248,2302,12795,31.394921,Alabama,...,0.056484,0.57,0.14,0.23,0.06,105229.1,25845.8,42460.9,11076.8,115107.0
93,"Lauderdale County, Alabama",Lauderdale County,92590,41.5,44888,25803,2798,14701,15.877525,Alabama,...,0.030219,0.34,0.14,0.27,0.25,62768.3,25845.8,49845.4,46153.1,100764.0
94,"Lowndes County, Alabama",Lowndes County,10362,40.7,29785,18976,446,3095,29.868751,Alabama,...,0.043042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,"Macon County, Alabama",Macon County,19358,38.0,32308,19564,1251,4380,22.626304,Alabama,...,0.064624,0.55,0.22,0.25,-0.02,101536.9,40614.8,46153.1,-3692.3,105436.0
96,"Limestone County, Alabama",Limestone County,91695,39.1,52831,26685,2957,13138,14.327935,Alabama,...,0.032248,0.35,0.15,0.32,0.18,64614.4,27691.9,59076.0,33230.3,91200.0
97,"Shelby County, Alabama",Shelby County,208721,38.5,74063,35330,4650,17127,8.205691,Alabama,...,0.022279,0.29,0.17,0.33,0.21,53537.6,31384.1,60922.1,38768.6,112024.0
98,"St. Clair County, Alabama",St. Clair County,86937,40.1,53483,24686,2354,11656,13.407410,Alabama,...,0.027077,0.36,0.13,0.31,0.20,66460.5,23999.6,57229.9,36922.5,147531.0
99,"Winston County, Alabama",Winston County,23968,44.6,35362,20580,925,4395,18.336949,Alabama,...,0.038593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
all_data.dtypes

Name                   object
County                 object
Population              int64
MedianAge             float64
HouseholdIncome         int64
PerCapitaIncome         int64
UnemploymentCount       int64
PovertyCount            int64
PovertyRate           float64
State                  object
abbr                   object
UnemploymentRate      float64
MedicialPercent       float64
StudentDebtPercent    float64
AutoDebtPercent       float64
OtherPercent          float64
MedicialAmount        float64
StudentDebtAmount     float64
AutoDebtAmount        float64
OtherAmount            object
TotalDebt             float64
dtype: object

In [41]:
#Group by State
all_data_byState = all_data.groupby(['State','abbr']).agg({'Population':'sum',
                                                           'MedianAge':'mean',
                                                           'HouseholdIncome':'mean',
                                                           'PerCapitaIncome':'mean',
                                                           'UnemploymentCount':'mean',
                                                           'PovertyCount':'mean',
                                                           'PovertyRate':'mean',
                                                           'UnemploymentRate':'mean',
                                                           'MedicialPercent':'mean',
                                                           'StudentDebtPercent':'mean',
                                                           'AutoDebtPercent':'mean',
                                                           'OtherPercent':'mean',
                                                           'MedicalAmount':'mean',
                                                           'StudentDebtAmount':'mean',
                                                           'AutoDebtAmount':'mean',
                                                           'OtherAmount':'mean',
                                                           'TotalDebt':'mean'}).reset_index()
all_data_byState.head()

C:\Users\maden\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py:4658: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

KeyError: 'MedicialAmount'

In [34]:
all_data_byState.describe()

,Population,MedianAge,HouseholdIncome,PerCapitaIncome,UnemploymentCount,PovertyCount,PovertyRate,UnemploymentRate,MedicialPercent,StudentDebtPercent,AutoDebtPercent,OtherPercent,MedicialAmount,StudentDebtAmount,AutoDebtAmount,TotalDebt
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,149366.670645,41.271808,52944.144683,27877.116704,5163.939141,20280.430850,15.141616,0.030381,0.314273,0.157263,0.314580,0.213884,58018.821540,29032.668780,58075.392335,106349.097774
std,162541.865911,2.340762,11389.695657,6258.315444,6447.543441,22969.477768,5.951443,0.008570,0.081146,0.025392,0.036537,0.071191,14980.517087,4687.647989,6745.111284,18269.678997
min,12961.272727,33.900000,18412.948718,10244.961538,209.150943,1497.622642,8.841534,0.013345,0.166122,0.102500,0.180000,0.080000,30668.300000,18922.775000,33230.300000,77003.631579
25%,43281.893462,40.102355,45500.417500,23291.576316,1319.540287,6746.218954,11.537021,0.024981,0.251230,0.138737,0.295816,0.174333,46380.234127,25612.573684,54611.344932,97214.750000
50%,81589.777778,41.495938,51902.878506,27248.410873,2422.203125,11985.037313,13.830043,0.031096,0.304643,0.160896,0.317143,0.212500,56240.882143,29703.335821,58548.540816,102707.125000
75%,185609.745695,42.952919,59101.102699,30455.594212,6434.133231,23677.437500,16.900655,0.033779,0.389679,0.172903,0.330526,0.267500,71939.713782,31920.150022,61019.169879,115746.900000
max,672391.000000,45.906250,77649.000000,50832.000000,31279.000000,111025.000000,48.411570,0.063988,0.482000,0.210000,0.408333,0.410000,88983.240000,38768.600000,75383.441667,180761.500000

In [35]:
all_data_byState.dtypes

State                  object
abbr                   object
Population            float64
MedianAge             float64
HouseholdIncome       float64
PerCapitaIncome       float64
UnemploymentCount     float64
PovertyCount          float64
PovertyRate           float64
UnemploymentRate      float64
MedicialPercent       float64
StudentDebtPercent    float64
AutoDebtPercent       float64
OtherPercent          float64
MedicialAmount        float64
StudentDebtAmount     float64
AutoDebtAmount        float64
TotalDebt             float64
dtype: object

In [36]:
#Save to a csv files
all_data_byState.to_csv("county_census_debt_data_byState.csv",encoding ="utf-8",index=False)